# _config.yml

url: "https://tabletopadventures.github.io"
baseurl: ""
repository: "TabletopAdventures/tabletopadventures.github.io"

title: Tabletop Adventures
description: "A timeline of our TTRPG campaigns."
theme: jekyll-theme-minimal # You can change this later

# Tell Jekyll to process these folders
include:
  - "_pages"

# Set the folder where all campaigns live so they're not top-level
collections_dir: campaigns

# Collections: Define each campaign here
collections:
  shadowrun_zero:
    output: true # Creates a page at /shadowrun_zero/
    title: "Shadowrun Zero"
    permalink: /:collection/:name/
    icon: "/assets/images/shadowrun_zero/campaign_icon.png"
    description: "In the sprawling, sun-scorched metroplex of Dallas-Fort Worth, shadowrunners are puppeted by their corporate overlords, serving as deniable assets and expendable pawns in the silent wars fought in the city's shimmering data-havens and chrome-lined boardrooms."

  m_and_m_foundation:
    output: true # Creates a page at /m_and_m_foundation/
    title: "M&M Foundation"
    permalink: /:collection/:name/
    icon: "/assets/images/m_and_m_foundation/campaign_icon.png"

  horror_on_the_orient_express:
    output: true 
    title: "Horror on the Orient Express"
    permalink: /:collection/:name/
    icon: "/assets/images/horror_on_the_orient_express/HotOE-Icon.webp"

# Defaults for all pages and collections
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
