# _config.yml

url: "https://tabletopadventures.github.io"
baseurl: ""
repository: "TabletopAdventures/tabletopadventures.github.io"

title: Tabletop Adventures
description: "A timeline of our TTRPG campaigns."
theme: jekyll-theme-minimal # You can change this later

# Tell Jekyll to process these folders
include:
  - "_pages"

# Set the folder where all campaigns live so they're not top-level
collections_dir: campaigns

# Collections: Define each campaign here
collections:
  k-macmillan-shadowrun_zero:
    output: true # Creates a page at /shadowrun_zero/
    title: "Shadowrun Zero"
    permalink: /:collection/:name/
    icon: "/assets/images/k-macmillan/shadowrun_zero/campaign_icon.png"
    description: "In the sprawling, sun-scorched metroplex of Dallas-Fort Worth, shadowrunners are puppeted by their corporate overlords, serving as deniable assets and expendable pawns in the silent wars fought in the city's shimmering data-havens and chrome-lined boardrooms."

  katiemacmillan-m_and_m_foundation:
    output: true # Creates a page at /m_and_m_foundation/
    title: "M&M Foundation"
    permalink: /:collection/:name/
    icon: "/assets/images/katiemacmillan/m_and_m_foundation/campaign_icon.png"

  Tyler-Henson-horror_on_the_orient_express:
    output: true 
    title: "Horror on the Orient Express"
    permalink: /:collection/:name/
    icon: "/assets/images/Tyler-Henson/horror_on_the_orient_express/HotOE-Icon.webp"
    description: "In 1923, an heiress to a criminal empire and her entourage collect the pieces of a dark artifact from all across Europe to finally destroy it, battling the cultists to a flayed god, evading \"Sloppy Joe,\" and ignoring the ominous appearances of a woman who is definitely not a vampire."

# Defaults for all pages and collections
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
